export const DEFAULT_COMPANY_ENVIRONMENT = "general";

export const COMPANY_ENVIRONMENTS = [
  {
    id: "general",
    label: "Allgemein",
    organizationLabel: "Einrichtung",
    organizationLabelWithArticle: "der Einrichtung",
    accountTitle: "Konto einrichten",
    accountNameLabel: "Name der Einrichtung",
    accountNamePlaceholder: "z. B. Servicepunkt Mitte",
    settingsTitle: "Einstellungen",
    dataTitle: "Einrichtungsdaten",
    workerSingular: "Mitarbeiter",
    workerPlural: "Mitarbeitende",
    workerCountLabel: "Anzahl der Mitarbeitenden",
    workerSectionTitle: "Mitarbeitende und Zeiten",
    workerNamePlaceholder: "z. B. Team 1",
    ticketAssignmentLabel: "Zuordnung",
    customerGroup: "Kunden",
    searchNameLabel: "Einrichtung oder Unternehmen",
  },
  {
    id: "doctor",
    label: "Arzt",
    organizationLabel: "Praxis",
    organizationLabelWithArticle: "der Praxis",
    accountTitle: "Praxis einrichten",
    accountNameLabel: "Name der Praxis",
    accountNamePlaceholder: "z. B. Hausarzt Müller",
    settingsTitle: "Praxis-Einstellungen",
    dataTitle: "Praxisdaten",
    workerSingular: "Arzt",
    workerPlural: "Ärzte",
    workerCountLabel: "Anzahl von Ärzten",
    workerSectionTitle: "Ärzte und Zeiten",
    workerNamePlaceholder: "z. B. Dr. Meyer",
    ticketAssignmentLabel: "Arzt",
    customerGroup: "Patienten",
    searchNameLabel: "Praxis oder Unternehmen",
  },
  {
    id: "veterinarian",
    label: "Tierarzt",
    organizationLabel: "Tierarztpraxis",
    organizationLabelWithArticle: "der Tierarztpraxis",
    accountTitle: "Tierarztpraxis einrichten",
    accountNameLabel: "Name der Tierarztpraxis",
    accountNamePlaceholder: "z. B. Tierarztpraxis am Park",
    settingsTitle: "Tierarztpraxis-Einstellungen",
    dataTitle: "Praxisdaten",
    workerSingular: "Tierarzt",
    workerPlural: "Tierärzte",
    workerCountLabel: "Anzahl von Tierärzten",
    workerSectionTitle: "Tierärzte und Zeiten",
    workerNamePlaceholder: "z. B. Dr. Klein",
    ticketAssignmentLabel: "Tierarzt",
    customerGroup: "Tierhalter",
    searchNameLabel: "Tierarztpraxis oder Unternehmen",
  },
  {
    id: "hairdresser",
    label: "Friseur",
    organizationLabel: "Friseursalon",
    organizationLabelWithArticle: "des Friseursalons",
    accountTitle: "Friseursalon einrichten",
    accountNameLabel: "Name des Friseursalons",
    accountNamePlaceholder: "z. B. Salon Schnittpunkt",
    settingsTitle: "Salon-Einstellungen",
    dataTitle: "Salondaten",
    workerSingular: "Friseur",
    workerPlural: "Friseure",
    workerCountLabel: "Anzahl der Friseure",
    workerSectionTitle: "Friseure und Zeiten",
    workerNamePlaceholder: "z. B. Alex",
    ticketAssignmentLabel: "Friseur",
    customerGroup: "Kunden",
    searchNameLabel: "Friseursalon oder Unternehmen",
  },
  {
    id: "authority",
    label: "Behörde (Jobcenter, Amt)",
    organizationLabel: "Behörde",
    organizationLabelWithArticle: "der Behörde",
    accountTitle: "Behörde einrichten",
    accountNameLabel: "Name der Behörde",
    accountNamePlaceholder: "z. B. Bürgeramt Mitte",
    settingsTitle: "Behörden-Einstellungen",
    dataTitle: "Standortdaten",
    workerSingular: "Mitarbeiter",
    workerPlural: "Mitarbeitende",
    workerCountLabel: "Anzahl der Mitarbeitenden",
    workerSectionTitle: "Mitarbeitende und Zeiten",
    workerNamePlaceholder: "z. B. Schalter 1",
    ticketAssignmentLabel: "Mitarbeiter",
    customerGroup: "Besucher",
    searchNameLabel: "Behörde oder Standort",
  },
  {
    id: "club",
    label: "Diskothek",
    organizationLabel: "Diskothek",
    organizationLabelWithArticle: "der Diskothek",
    accountTitle: "Diskothek einrichten",
    accountNameLabel: "Name der Diskothek",
    accountNamePlaceholder: "z. B. Club Nachtlicht",
    settingsTitle: "Club-Einstellungen",
    dataTitle: "Clubdaten",
    workerSingular: "Mitarbeiter",
    workerPlural: "Mitarbeitende",
    workerCountLabel: "Anzahl der Mitarbeitenden",
    workerSectionTitle: "Mitarbeitende und Zeiten",
    workerNamePlaceholder: "z. B. Einlass 1",
    ticketAssignmentLabel: "Bereich",
    customerGroup: "Gäste",
    searchNameLabel: "Diskothek oder Club",
  },
  {
    id: "gastronomy",
    label: "Gastronomie",
    organizationLabel: "Gastronomiebetrieb",
    organizationLabelWithArticle: "des Gastronomiebetriebs",
    accountTitle: "Gastronomie einrichten",
    accountNameLabel: "Name des Betriebs",
    accountNamePlaceholder: "z. B. Café am Markt",
    settingsTitle: "Gastronomie-Einstellungen",
    dataTitle: "Betriebsdaten",
    workerSingular: "Mitarbeiter",
    workerPlural: "Mitarbeitende",
    workerCountLabel: "Anzahl der Mitarbeitenden",
    workerSectionTitle: "Mitarbeitende und Zeiten",
    workerNamePlaceholder: "z. B. Service 1",
    ticketAssignmentLabel: "Mitarbeiter",
    customerGroup: "Gäste",
    searchNameLabel: "Restaurant, Café oder Betrieb",
  },
  {
    id: "optician",
    label: "Optiker",
    organizationLabel: "Optiker",
    organizationLabelWithArticle: "des Optikers",
    accountTitle: "Optiker einrichten",
    accountNameLabel: "Name des Optikers",
    accountNamePlaceholder: "z. B. Optik Schmidt",
    settingsTitle: "Optiker-Einstellungen",
    dataTitle: "Standortdaten",
    workerSingular: "Optiker",
    workerPlural: "Optiker",
    workerCountLabel: "Anzahl der Optiker",
    workerSectionTitle: "Optiker und Zeiten",
    workerNamePlaceholder: "z. B. Beratung 1",
    ticketAssignmentLabel: "Optiker",
    customerGroup: "Kunden",
    searchNameLabel: "Optiker oder Unternehmen",
  },
  {
    id: "hearing_aid",
    label: "Hörgeräteakustiker",
    organizationLabel: "Hörakustiker",
    organizationLabelWithArticle: "des Hörakustikers",
    accountTitle: "Hörakustiker einrichten",
    accountNameLabel: "Name des Hörakustikers",
    accountNamePlaceholder: "z. B. Hörakustik Zentrum",
    settingsTitle: "Hörakustiker-Einstellungen",
    dataTitle: "Standortdaten",
    workerSingular: "Hörakustiker",
    workerPlural: "Hörakustiker",
    workerCountLabel: "Anzahl der Hörakustiker",
    workerSectionTitle: "Hörakustiker und Zeiten",
    workerNamePlaceholder: "z. B. Beratung 1",
    ticketAssignmentLabel: "Hörakustiker",
    customerGroup: "Kunden",
    searchNameLabel: "Hörakustiker oder Unternehmen",
  },
  {
    id: "event",
    label: "Messen/Events",
    organizationLabel: "Event",
    organizationLabelWithArticle: "des Events",
    accountTitle: "Event einrichten",
    accountNameLabel: "Name des Events",
    accountNamePlaceholder: "z. B. Messe Eingang Nord",
    settingsTitle: "Event-Einstellungen",
    dataTitle: "Eventdaten",
    workerSingular: "Mitarbeiter",
    workerPlural: "Mitarbeitende",
    workerCountLabel: "Anzahl der Mitarbeitenden",
    workerSectionTitle: "Mitarbeitende und Zeiten",
    workerNamePlaceholder: "z. B. Stand 1",
    ticketAssignmentLabel: "Bereich",
    customerGroup: "Besucher",
    searchNameLabel: "Event, Messe oder Standort",
  },
] as const;

export type CompanyEnvironment = (typeof COMPANY_ENVIRONMENTS)[number]["id"];

export function isCompanyEnvironment(value: unknown): value is CompanyEnvironment {
  return (
    typeof value === "string" &&
    COMPANY_ENVIRONMENTS.some((environment) => environment.id === value)
  );
}

export function normalizeCompanyEnvironment(value: unknown): CompanyEnvironment {
  return isCompanyEnvironment(value) ? value : DEFAULT_COMPANY_ENVIRONMENT;
}

export function getCompanyEnvironmentCopy(value: unknown) {
  const environmentType = normalizeCompanyEnvironment(value);

  return (
    COMPANY_ENVIRONMENTS.find(
      (environment) => environment.id === environmentType
    ) ?? COMPANY_ENVIRONMENTS[0]
  );
}
